### ISSUE TITLE
Add global boolean for AWS LoadBalancer

### ISSUE THREAD

**Issue by jwalcorn** [IBMStockTrader/stocktrader-operator#16]
Today, to expose the Trader UI to be callable from a browser on your laptop, we have to manually create a special type of Service that exposes it via a Load Balancer, with an AWS-specific annotation.  Need to teach the operator to do that for us, when requested.  Here's the yaml we're manually running today:

```
apiVersion: v1
kind: Service
metadata:
  name: trader-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: example-stocktrader-trader
spec:
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 9080
  - name: https
    protocol: TCP
    port: 9443
    targetPort: 9443
  selector:
    app: trader
  sessionAffinity: None
  type: LoadBalancer
  ```
